version: '3.9'


services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    depends_on:
      - php
      - mysql
    ports:
      - 8007:80
      - 4443:443
    volumes: 
      - ./wordpress:/var/www/html:delegated
  mysql:
    image: mysql:latest
    container_name: wordpress-mysql-db
    volumes:
      - ./db/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=sadat
      - MYSQL_PASSWORD=secret
    ports:
        - "3306:3306"
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./wordpress:/var/www/html:delegated

  wp:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./wordpress:/var/www/html:delegated
    entrypoint: ['wp', '--allow-root']